---
- name: Start loader
  hosts: stress
  become: True

  tasks: 
    - name: Start CQL Stress
      ansible.builtin.systemd_service:
        name: cassandra-stress.service
        state: started
        daemon_reload: True

